version: 1
formatters:
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: detailed
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/bikestores_app.log
    maxBytes: 10485760
    backupCount: 5
loggers:
  synonym_learner:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  query_processor:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  name_match_manager:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  table_identifier:
    level: DEBUG
    handlers: [console, file]
    propagate: no
root:
  level: INFO
  handlers: [console, file]