version: 1
disable_existing_loggers: false
formatters:
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: detailed
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/bikestores_app.log
    maxBytes: 10485760
    backupCount: 5
loggers:
  analyzer:
    level: DEBUG
    handlers: [console, file]
    propagate: false
  synonym_learner:
    level: DEBUG
    handlers: [console, file]
    propagate: false
  query_processor:
    level: DEBUG
    handlers: [console, file]
    propagate: false
  name_match_manager:
    level: DEBUG
    handlers: [console, file]
    propagate: false
  table_identifier:
    level: DEBUG
    handlers: [console, file]
    propagate: false
  interface:
    level: DEBUG
    handlers: [console, file]
    propagate: false
  nlp_pipeline:
    level: DEBUG
    handlers: [console, file]
    propagate: false
  patterns:
    level: DEBUG
    handlers: [console, file]
    propagate: false
root:
  level: INFO
  handlers: [console, file]